name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        
    - name: Build for Windows
      run: |
        GOOS=windows GOARCH=amd64 go build -o go-win-printer-info-windows-amd64.exe ./cmd/example

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          go-win-printer-info-windows-amd64.exe
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
